### ISSUE TITLE
Footer large sous macOS

### ISSUE THREAD

**Issue by AnCaRioN** [TrAsKiN/owl-buvette#1]
Salut Traskin,

Sur un macbook pro retina, que ce soit sous firefox/safari/chrome, le footer est large (cf screenshot)

Si t'as besoin d'infos n'hésites pas :)

<img width="1274" alt="Capture d’écran 2020-12-11 à 17 03 39" src="https://user-images.githubusercontent.com/42072/101926369-5ed3a900-3bd3-11eb-9526-da1a71566630.png">

**Comment by TrAsKiN** [comment]
Le soucis vient du fait que le ratio prévu pour la page est 16:9 mais qu'il s'agit ici d'un ratio de 16:10.
